// Build pipeline invariants — scripts/build-modal.mjs + lib inline markers.

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const read = (p) => readFileSync(join(ROOT, p), "utf8");

const fzfSrc  = read("lib/fzf.js");
const utilSrc = read("lib/util.js");
const tmpl    = read("modal/content.template.js");
const built   = read("modal/content.js");
const buildJs = read("scripts/build-modal.mjs");

test("lib/fzf.js declares FZF_INLINE_START/END markers on their own lines", () => {
  assert.match(fzfSrc, /^\/\/ FZF_INLINE_START\n/m);
  assert.match(fzfSrc, /^\/\/ FZF_INLINE_END$/m);
});

test("lib/util.js declares UTIL_INLINE_START/END markers on their own lines", () => {
  assert.match(utilSrc, /^\/\/ UTIL_INLINE_START\n/m);
  assert.match(utilSrc, /^\/\/ UTIL_INLINE_END$/m);
});

test("FZF inline block exports fzfMatch and highlightWithIndices", () => {
  const block = fzfSrc.match(/^\/\/ FZF_INLINE_START\n([\s\S]*?)\n\/\/ FZF_INLINE_END$/m)[1];
  assert.match(block, /export function fzfMatch/);
  assert.match(block, /export function highlightWithIndices/);
});

test("UTIL inline block exports tab-tree and frecency helpers", () => {
  const block = utilSrc.match(/^\/\/ UTIL_INLINE_START\n([\s\S]*?)\n\/\/ UTIL_INLINE_END$/m)[1];
  for (const fn of ["hostnameOf", "buildTabTree", "flattenTree", "domainHueFor", "frecencyScore"]) {
    assert.match(block, new RegExp(`export function ${fn}`));
  }
});

test("build-modal.mjs requires ZPWR_ROOT env var", () => {
  assert.match(buildJs, /if \(!ROOT\)/);
  assert.match(buildJs, /process\.exit\(1\)/);
});

test("build-modal.mjs reads ShareTechMono and Orbitron font files", () => {
  assert.match(buildJs, /fonts\/ShareTechMono-Regular\.woff2/);
  assert.match(buildJs, /fonts\/Orbitron\.woff2/);
});

test("build-modal.mjs strips export keyword when inlining fzf and util", () => {
  assert.match(buildJs, /\.replace\(\/\^export \/gm, ""\)/);
});

test("build-modal.mjs substitutes all marker occurrences (replaceAll)", () => {
  assert.match(buildJs, /\.replaceAll\("%%STM%%", stm\)/);
  assert.match(buildJs, /\.replaceAll\("%%ORB%%", orb\)/);
  assert.match(buildJs, /\.replaceAll\("%%FZF%%", fzfBody\)/);
  assert.match(buildJs, /\.replaceAll\("%%UTIL%%", utilBody\)/);
});

test("build-modal.mjs fails if template markers are missing", () => {
  assert.match(buildJs, /template missing %%STM%%/);
  assert.match(buildJs, /process\.exit\(2\)/);
});

test("build-modal.mjs writes generated banner to modal/content.js", () => {
  assert.match(buildJs, /THIS FILE IS GENERATED by scripts\/build-modal\.sh/);
});

test("modal/content.js contains the do-not-edit generated banner", () => {
  assert.match(built, /THIS FILE IS GENERATED by scripts\/build-modal\.sh/);
});

test("modal/content.js inlines fzfMatch (no ES import)", () => {
  assert.match(built, /function fzfMatch\(/);
  assert.ok(!/^import .*fzf/m.test(built), "built modal must not ES-import fzf");
});

test("modal/content.js inlines buildTabTree from util", () => {
  assert.match(built, /function buildTabTree\(/);
});

test("modal/content.js embeds base64 font data (not chrome-extension URLs)", () => {
  const content = read("modal/content.js");
  assert.match(content, /data:font\/woff2;base64,/);
  assert.ok(!content.includes('= "%%STM%%"'), "FONT_STM must be substituted by build");
});

test("modal/content.js no longer contains %% substitution markers", () => {
  const content = read("modal/content.js");
  for (const m of ["%%STM%%", "%%ORB%%", "%%FZF%%", "%%UTIL%%"]) {
    assert.ok(!content.includes(m), `built file still has marker ${m}`);
  }
});

test("scripts/build-modal.sh invokes build-modal.mjs with ZPWR_ROOT", () => {
  const sh = read("scripts/build-modal.sh");
  assert.match(sh, /build-modal\.mjs/);
  assert.match(sh, /ZPWR_ROOT/);
});

test("scripts/gen.sh calls build-modal.sh (modal stays in sync with template)", () => {
  const sh = read("scripts/gen.sh");
  assert.match(sh, /build-modal\.sh/);
});

test("font files referenced by build script exist on disk", () => {
  for (const f of ["fonts/ShareTechMono-Regular.woff2", "fonts/Orbitron.woff2"]) {
    assert.ok(existsSync(join(ROOT, f)), `missing ${f}`);
  }
});

test("running build-modal.sh is idempotent (second run matches first)", () => {
  execFileSync("bash", ["scripts/build-modal.sh"], {
    cwd: ROOT,
    env: { ...process.env, ZPWR_ROOT: ROOT },
    stdio: "pipe"
  });
  const once = read("modal/content.js");
  execFileSync("bash", ["scripts/build-modal.sh"], {
    cwd: ROOT,
    env: { ...process.env, ZPWR_ROOT: ROOT },
    stdio: "pipe"
  });
  const twice = read("modal/content.js");
  assert.equal(twice, once, "build-modal.sh must be idempotent");
});

test("lib/fzf.js scoring constants match audio-haxor canonical values", () => {
  assert.match(fzfSrc, /FZF_SCORE_MATCH = 16/);
  assert.match(fzfSrc, /FZF_BONUS_BOUNDARY = 9/);
  assert.match(fzfSrc, /FZF_BONUS_CONSECUTIVE = 4/);
});

test("template still contains marker placeholders before build", () => {
  for (const m of ["%%STM%%", "%%ORB%%", "%%FZF%%", "%%UTIL%%"]) {
    assert.ok(tmpl.includes(m), `template lost marker ${m}`);
  }
});
