// docs/index.html landing page invariants (generated by scripts/gen.mjs).

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const docs = readFileSync(join(ROOT, "docs/index.html"), "utf8");
const manifest = JSON.parse(readFileSync(join(ROOT, "manifest.json"), "utf8"));
const commandCount = Object.keys(manifest.commands).length;

test("docs/index.html exists and uses dark theme", () => {
  assert.ok(existsSync(join(ROOT, "docs/index.html")));
  assert.match(docs, /data-theme="dark"/);
});

test("docs/index.html meta description includes dynamic command count", () => {
  assert.match(docs, new RegExp(`${commandCount} keyboard`));
});

test("docs/index.html tagline mentions MenkeTechnologies", () => {
  assert.match(docs, /MenkeTechnologies/);
});

test("docs/index.html links to GitHub source repo", () => {
  assert.match(docs, /github\.com\/MenkeTechnologies\/zpwrchrome/);
});

test("docs/index.html footer includes manifest version", () => {
  assert.match(docs, new RegExp(`v${manifest.version.replace(/\./g, "\\.")}`));
});

test("docs/index.html loads Orbitron and Share Tech Mono from Google Fonts", () => {
  assert.match(docs, /fonts\.googleapis\.com/);
  assert.match(docs, /Orbitron/);
  assert.match(docs, /Share\+Tech\+Mono/);
});

test("docs/index.html defines strykelang cyan accent on :root", () => {
  assert.match(docs, /--cyan:\s+#05d9e8/);
});

test("docs/index.html defines accent magenta on :root", () => {
  assert.match(docs, /--accent:\s+#ff2a6d/);
});

test("docs/index.html includes cyber grid background on body", () => {
  assert.match(docs, /--cyber-grid-line/);
  assert.match(docs, /background-size:.*52px 52px/);
});

test("docs/index.html has primary CTA button to GitHub", () => {
  assert.match(docs, /class="btn btn-primary"/);
  assert.match(docs, /source on github/i);
});

test("docs/index.html install section includes git clone command", () => {
  assert.match(docs, /git clone https:\/\/github\.com\/MenkeTechnologies\/zpwrchrome\.git/);
});

test("docs/index.html references engineering report page", () => {
  assert.match(docs, /report\.html|engineering report/i);
});

test("docs/index.html mentions chrome.userScripts or userscripts feature", () => {
  assert.match(docs, /userScripts|userscript/i);
});

test("docs/index.html mentions fzf or live filter search", () => {
  assert.match(docs, /fzf|live.filter|filter/i);
});

test("docs/index.html uses MIT license in footer", () => {
  assert.match(docs, /MIT/);
});

test("docs/index.html charset is utf-8", () => {
  assert.match(docs, /<meta charset="utf-8">/);
});
