# typed: false
# frozen_string_literal: true
#
# Homebrew formula for the zpwrchrome native messaging host.
#
# Lives in the MenkeTechnologies/homebrew-zpwrchrome tap. Copy this file to
# that tap's Formula/ directory and bump url + sha256 on each release tag.
#
#   brew tap MenkeTechnologies/zpwrchrome
#   brew install zpwr-chrome-host
#   zpwr-chrome-host-register <chrome-extension-id>
#
class ZpwrChromeHost < Formula
  desc "Native host for the zpwrchrome extension (UNIX `pass` + segmented downloads)"
  homepage "https://github.com/MenkeTechnologies/zpwrchrome"
  url "https://github.com/MenkeTechnologies/zpwrchrome/archive/refs/tags/v0.5.0.tar.gz"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"
  head "https://github.com/MenkeTechnologies/zpwrchrome.git", branch: "main"

  depends_on "rust" => :build

  def install
    cd "host" do
      system "cargo", "install", *std_cargo_args
    end

    # Ship the registration script so users can wire Chrome to the host with
    # one command (`zpwr-chrome-host-register <ext-id>`). It writes the
    # native-messaging manifest pointing at #{bin}/zpwr-chrome-host.
    (libexec/"install.sh").write <<~BASH
      #!/usr/bin/env bash
      # Auto-generated by Homebrew formula. See `host/install.sh` in the repo.
      set -euo pipefail
      if [[ $# -lt 1 ]]; then
        echo "usage: $(basename "$0") <chrome-extension-id> [<ext-id> ...]" >&2
        exit 1
      fi
      HOST_NAME=com.menketechnologies.zpwrchrome
      BIN="#{opt_bin}/zpwr-chrome-host"
      origins=""
      for id in "$@"; do
        origins+="    \\"chrome-extension://${id}/\\""
        if [[ "$id" != "${!#}" ]]; then origins+=$',\\n'; fi
      done
      case "$(uname -s)" in
        Darwin) dirs=(
          "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
          "$HOME/Library/Application Support/Chromium/NativeMessagingHosts"
          "$HOME/Library/Application Support/BraveSoftware/Brave-Browser/NativeMessagingHosts"
          "$HOME/Library/Application Support/Microsoft Edge/NativeMessagingHosts"
        );;
        Linux)  dirs=(
          "$HOME/.config/google-chrome/NativeMessagingHosts"
          "$HOME/.config/chromium/NativeMessagingHosts"
          "$HOME/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts"
          "$HOME/.config/microsoft-edge/NativeMessagingHosts"
        );;
        *) echo "unsupported os: $(uname -s)" >&2; exit 1;;
      esac
      manifest=$(cat <<JSON
      {
        "name": "${HOST_NAME}",
        "description": "zpwrchrome native host: pass + downloads",
        "path": "${BIN}",
        "type": "stdio",
        "allowed_origins": [
      ${origins}
        ]
      }
      JSON
      )
      installed=0
      for d in "${dirs[@]}"; do
        parent="$(dirname "$d")"
        [[ -d "$parent" ]] || continue
        mkdir -p "$d"
        printf '%s\\n' "$manifest" > "$d/${HOST_NAME}.json"
        echo "installed: $d/${HOST_NAME}.json"
        installed=$((installed + 1))
      done
      [[ $installed -gt 0 ]] || { echo "no Chromium-family browser dirs found" >&2; exit 2; }
    BASH
    chmod 0755, libexec/"install.sh"

    (bin/"zpwr-chrome-host-register").write <<~BASH
      #!/usr/bin/env bash
      exec "#{libexec}/install.sh" "$@"
    BASH
    chmod 0755, bin/"zpwr-chrome-host-register"
  end

  def caveats
    <<~EOS
      To connect Chrome to this host, register the native-messaging manifest:

        zpwr-chrome-host-register <chrome-extension-id>

      Find the ID at chrome://extensions with Developer mode enabled.

      Then load the extension from
        https://github.com/MenkeTechnologies/zpwrchrome
      and bind shortcuts (pass-fill, pass-copy-pw, pass-copy-otp, dl-paste-url,
      etc.) at chrome://extensions/shortcuts.
    EOS
  end

  test do
    assert_match(/#{Regexp.escape(version.to_s)}/,
                 shell_output("#{bin}/zpwr-chrome-host --version"))
    assert_match(/UNIX `pass`|pass \(list\/match/i,
                 shell_output("#{bin}/zpwr-chrome-host --help"))
  end
end
