import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.env.ZPWR_ROOT;
if (!ROOT) {
  console.error("ZPWR_ROOT not set");
  process.exit(1);
}

const tmpl = readFileSync(join(ROOT, "modal/content.template.js"), "utf8");
const stm  = readFileSync(join(ROOT, "fonts/ShareTechMono-Regular.woff2")).toString("base64");
const orb  = readFileSync(join(ROOT, "fonts/Orbitron.woff2")).toString("base64");

// Inline lib/fzf.js between FZF_INLINE_START / FZF_INLINE_END markers,
// stripping `export ` so it works inside the content script's IIFE.
const fzfSrc = readFileSync(join(ROOT, "lib/fzf.js"), "utf8");
const fzfMatch = fzfSrc.match(/^\/\/ FZF_INLINE_START\n([\s\S]*?)\n\/\/ FZF_INLINE_END$/m);
if (!fzfMatch) {
  console.error("lib/fzf.js missing FZF_INLINE_START / FZF_INLINE_END markers on their own lines");
  process.exit(3);
}
const fzfBody = fzfMatch[1].replace(/^export /gm, "");

if (!tmpl.includes("%%STM%%") || !tmpl.includes("%%ORB%%") || !tmpl.includes("%%FZF%%")) {
  console.error("template missing %%STM%% / %%ORB%% / %%FZF%% markers");
  process.exit(2);
}

const out = `// THIS FILE IS GENERATED by scripts/build-modal.sh from
// modal/content.template.js + fonts/*.woff2 + lib/fzf.js. Do not edit
// by hand — edit the template (or lib/fzf.js for the fuzzy-match algo)
// then run scripts/build-modal.sh (or scripts/gen.sh which calls it).

${tmpl.replace("%%STM%%", stm).replace("%%ORB%%", orb).replace("%%FZF%%", fzfBody)}`;

writeFileSync(join(ROOT, "modal/content.js"), out);
