import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.env.ZPWR_ROOT;
if (!ROOT) {
  console.error("ZPWR_ROOT not set");
  process.exit(1);
}

const tmpl = readFileSync(join(ROOT, "modal/content.template.js"), "utf8");
const stm  = readFileSync(join(ROOT, "fonts/ShareTechMono-Regular.woff2")).toString("base64");
const orb  = readFileSync(join(ROOT, "fonts/Orbitron.woff2")).toString("base64");

// Inline lib/fzf.js between FZF_INLINE_START / FZF_INLINE_END markers,
// stripping `export ` so it works inside the content script's IIFE.
const fzfSrc = readFileSync(join(ROOT, "lib/fzf.js"), "utf8");
const fzfMatch = fzfSrc.match(/^\/\/ FZF_INLINE_START\n([\s\S]*?)\n\/\/ FZF_INLINE_END$/m);
if (!fzfMatch) {
  console.error("lib/fzf.js missing FZF_INLINE_START / FZF_INLINE_END markers on their own lines");
  process.exit(3);
}
const fzfBody = fzfMatch[1].replace(/^export /gm, "");

// Same trick for lib/util.js — the modal needs hostnameOf, buildTabTree,
// flattenTree, domainHueFor. Strip `export ` so the helpers become locals
// inside the modal's IIFE.
const utilSrc = readFileSync(join(ROOT, "lib/util.js"), "utf8");
const utilMatch = utilSrc.match(/^\/\/ UTIL_INLINE_START\n([\s\S]*?)\n\/\/ UTIL_INLINE_END$/m);
if (!utilMatch) {
  console.error("lib/util.js missing UTIL_INLINE_START / UTIL_INLINE_END markers on their own lines");
  process.exit(4);
}
const utilBody = utilMatch[1].replace(/^export /gm, "");

if (!tmpl.includes("%%STM%%") || !tmpl.includes("%%ORB%%") ||
    !tmpl.includes("%%FZF%%") || !tmpl.includes("%%UTIL%%")) {
  console.error("template missing %%STM%% / %%ORB%% / %%FZF%% / %%UTIL%% markers");
  process.exit(2);
}

const out = `// THIS FILE IS GENERATED by scripts/build-modal.sh from
// modal/content.template.js + fonts/*.woff2 + lib/fzf.js + lib/util.js.
// Do not edit by hand — edit the template (or lib/fzf.js / lib/util.js
// for the fuzzy-match algo and shared tab helpers) then run
// scripts/build-modal.sh (or scripts/gen.sh which calls it).

${tmpl
  .replace("%%STM%%", stm)
  .replace("%%ORB%%", orb)
  .replace("%%FZF%%", fzfBody)
  .replace("%%UTIL%%", utilBody)}`;

writeFileSync(join(ROOT, "modal/content.js"), out);
