import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = process.env.ZPWR_ROOT;
if (!ROOT) {
  console.error("ZPWR_ROOT not set");
  process.exit(1);
}

const tmpl = readFileSync(join(ROOT, "modal/content.template.js"), "utf8");
const stm  = readFileSync(join(ROOT, "fonts/ShareTechMono-Regular.woff2")).toString("base64");
const orb  = readFileSync(join(ROOT, "fonts/Orbitron.woff2")).toString("base64");

if (!tmpl.includes("%%STM%%") || !tmpl.includes("%%ORB%%")) {
  console.error("template missing %%STM%% / %%ORB%% markers");
  process.exit(2);
}

const out = `// THIS FILE IS GENERATED by scripts/build-modal.sh from
// modal/content.template.js + fonts/*.woff2. Do not edit by hand —
// edit the template, then run scripts/build-modal.sh (or scripts/gen.sh
// which calls it).

${tmpl.replace("%%STM%%", stm).replace("%%ORB%%", orb)}`;

writeFileSync(join(ROOT, "modal/content.js"), out);
